name: jarvis-local
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.0=py311haa95532_0
  - python=3.11.11=h4607a30_0
  - setuptools=75.8.0=py311haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.42=haa95532_4
  - vs2015_runtime=14.42.34433=he0abc0d_4
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - absl-py==2.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyascii==0.3.2
      - anyio==4.9.0
      - attrs==25.3.0
      - audioread==3.0.1
      - av==14.2.0
      - babel==2.17.0
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpathlib==0.21.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.3.1
      - coqpit-config==0.2.0
      - coqui-tts==0.26.0
      - coqui-tts-trainer==0.2.3
      - ctranslate2==4.5.0
      - cycler==0.12.1
      - cymem==2.0.11
      - cython==3.0.12
      - dateparser==1.1.8
      - decorator==5.2.1
      - deepspeed==0.16.5
      - diskcache==5.6.3
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - faster-whisper==1.1.1
      - filelock==3.13.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - grpcio==1.71.0
      - gruut==2.4.0
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.1
      - humanfriendly==10.0
      - idna==3.10
      - inflect==7.5.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonlines==1.2.0
      - keyboard==0.13.5
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - marisa-trie==1.2.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - monotonic-alignment-search==0.1.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.2.0
      - murmurhash==1.0.12
      - networkx==3.3
      - ninja==1.11.1.4
      - num2words==0.5.14
      - numba==0.61.0
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - ollama==0.4.7
      - onnxruntime==1.21.0
      - packaging==24.2
      - pillow==11.0.0
      - platformdirs==4.3.7
      - pooch==1.8.2
      - preshed==3.0.9
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pycparser==2.22
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyreadline3==3.5.4
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sounddevice==0.5.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - sudachidict-core==20250129
      - sudachipy==0.6.10
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - tqdm==4.67.1
      - transformers==4.50.3
      - typeguard==4.4.2
      - typer==0.15.2
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.3.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yarl==1.18.3
prefix: C:\Users\tudor\miniconda3\envs\jarvis-local
