name: parakeet
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - expat=2.7.4=hd7fb8db_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - pip=26.0.1=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.10.2=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.4.0
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alembic==1.18.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - av==16.1.0
      - backports-datetime-fromisoformat==2.0.3
      - braceexpand==0.1.7
      - certifi==2026.2.25
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - contourpy==1.3.2
      - ctranslate2==4.7.1
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.5
      - cycler==0.12.1
      - cytoolz==1.1.0
      - datasets==4.6.0
      - decorator==5.2.1
      - dill==0.4.0
      - editdistance==0.8.1
      - einops==0.8.2
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - faster-whisper==1.2.1
      - fiddle==0.3.0
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - graphviz==0.21
      - greenlet==3.3.2
      - grpcio==1.78.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - indic-numtowords==1.1.0
      - inflect==7.5.0
      - intervaltree==3.2.1
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiwer==3.1.0
      - joblib==1.5.3
      - kaldi-python-io==1.2.2
      - kaldialign==0.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lhotse==1.31.1
      - libcst==1.8.6
      - librosa==0.11.0
      - lightning==2.4.0
      - lightning-utilities==0.15.3
      - lilcom==1.8.2
      - llvmlite==0.46.0
      - mako==1.3.10
      - markdown==3.10.2
      - markupsafe==3.0.2
      - marshmallow==4.2.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mediapy==1.1.6
      - ml-dtypes==0.5.4
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - multiprocess==0.70.18
      - nemo-toolkit==2.6.2
      - networkx==3.4.2
      - numba==0.64.0
      - numba-cuda==0.15.1
      - numexpr==2.13.1
      - numpy==2.2.6
      - nv-one-logger-core==2.3.1
      - nv-one-logger-pytorch-lightning-integration==2.3.1
      - nv-one-logger-training-telemetry==2.3.1
      - omegaconf==2.3.0
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - optuna==4.7.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.3.3
      - parso==0.8.6
      - peft==0.18.1
      - pillow==12.0.0
      - platformdirs==4.9.2
      - pooch==1.9.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==5.29.6
      - psutil==7.2.2
      - pure-eval==0.2.3
      - pyannote-core==6.0.1
      - pyannote-database==6.1.1
      - pyannote-metrics==4.0.0
      - pyarrow==23.0.1
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.2.0
      - pyparsing==3.3.2
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.6.1
      - pytz==2025.2
      - pywin32==311
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - regex==2026.2.19
      - requests==2.32.5
      - resampy==0.4.3
      - ruamel-yaml==0.19.1
      - sacremoses==0.1.1
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.53.0
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - sox==1.5.0
      - soxr==1.0.0
      - sqlalchemy==2.0.47
      - stack-data==0.6.3
      - strenum==0.4.15
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - toml==0.10.2
      - tomli==2.4.0
      - toolz==1.1.0
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchmetrics==1.8.2
      - torchvision==0.21.0+cu124
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transformers==4.53.3
      - typeguard==4.5.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.3
      - wandb==0.25.0
      - wcwidth==0.6.0
      - webdataset==1.0.2
      - werkzeug==3.1.6
      - wget==3.2
      - whisper-normalizer==0.1.12
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\tudor\miniconda3\envs\parakeet
